# ============================================================================
# PROJECT CONFIGURATION
# ============================================================================
TARGET = abandonedwhere
CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O3 -DNDEBUG -march=native -flto

# Debug build option: make DEBUG=1
ifdef DEBUG
    CXXFLAGS = -std=c++17 -Wall -Wextra -O0 -g -DDEBUG
    $(info Building in DEBUG mode)
else
    $(info Building in RELEASE mode)
endif

# ============================================================================
# DIRECTORIES
# ============================================================================
SRC_DIR = .
OBJ_DIR = obj
BIN_DIR = .

# ============================================================================
# RAYLIB CONFIGURATION
# ============================================================================
RAYLIB_PREFIX ?= /usr/local
RAYLIB_INC = $(RAYLIB_PREFIX)/include
RAYLIB_LIBDIR = $(RAYLIB_PREFIX)/lib
RAYLIB_A = $(RAYLIB_LIBDIR)/libraylib.a

# System libraries for raylib (optimized linking order)
LIBS = -lGL -lm -lpthread -ldl -lrt -lX11

# ============================================================================
# SOURCE FILES
# ============================================================================
SOURCES = main.cpp \
          ConsoleCapture.cpp \
          ConfigParser.cpp \
          TextureLoader.cpp \
          UIRenderer.cpp \
          Player.cpp \
          GameConfig.cpp \
          GameState.cpp

OBJECTS = $(SOURCES:%.cpp=$(OBJ_DIR)/%.o)
EXECUTABLE = $(BIN_DIR)/$(TARGET)

# ============================================================================
# PARALLEL BUILDS
# ============================================================================
# Enable parallel builds by default
MAKEFLAGS += -j$(shell nproc 2>/dev/null || echo 1)

# ============================================================================
# BUILD RULES
# ============================================================================
.PHONY: all clean rebuild help debug release install

# Default target
all: $(EXECUTABLE)

# Debug build shortcut
debug:
	$(MAKE) DEBUG=1

# Release build shortcut  
release:
	$(MAKE) clean
	$(MAKE)

# Link executable with LTO support
$(EXECUTABLE): $(OBJECTS) | $(BIN_DIR)
	@echo "Linking $(TARGET)..."
	$(CXX) $(CXXFLAGS) $(OBJECTS) -o $@ $(RAYLIB_A) $(LIBS)
	@echo "Build complete: $@"

# Compile source files with dependency generation
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	@echo "Compiling $<..."
	$(CXX) $(CXXFLAGS) -I$(RAYLIB_INC) -MMD -MP -c $< -o $@

# ============================================================================
# DIRECTORY CREATION
# ============================================================================
$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

# ============================================================================
# UTILITY TARGETS
# ============================================================================
clean:
	@echo "Cleaning build files..."
	rm -rf $(OBJ_DIR)
	rm -f $(EXECUTABLE)
	@echo "Clean complete."

rebuild: clean all

install: $(EXECUTABLE)
	@echo "Installing to /usr/local/bin..."
	sudo cp $(EXECUTABLE) /usr/local/bin/
	@echo "Installation complete."

help:
	@echo "Available targets:"
	@echo "  all      - Build the game (default)"
	@echo "  debug    - Build with debug symbols"
	@echo "  release  - Clean build optimized for release"
	@echo "  clean    - Remove build files"
	@echo "  rebuild  - Clean and build"
	@echo "  install  - Install to system"
	@echo "  help     - Show this help"
	@echo ""
	@echo "Variables:"
	@echo "  DEBUG=1      - Enable debug build"
	@echo "  RAYLIB_PREFIX - Path to raylib installation (default: /usr/local)"

# ============================================================================
# DEPENDENCY TRACKING
# ============================================================================
# Include dependency files (auto-generated by -MMD -MP)
-include $(OBJECTS:.o=.d)

# ============================================================================
# EXPLICIT DEPENDENCIES (for reference)
# ============================================================================
$(OBJ_DIR)/main.o: main.cpp ConsoleCapture.h ConfigParser.h TextureLoader.h UIRenderer.h Player.h GameConfig.h GameState.h
$(OBJ_DIR)/ConsoleCapture.o: ConsoleCapture.cpp ConsoleCapture.h
$(OBJ_DIR)/ConfigParser.o: ConfigParser.cpp ConfigParser.h ConsoleCapture.h
$(OBJ_DIR)/TextureLoader.o: TextureLoader.cpp TextureLoader.h ConsoleCapture.h
$(OBJ_DIR)/UIRenderer.o: UIRenderer.cpp UIRenderer.h ConsoleCapture.h Version.h
$(OBJ_DIR)/Player.o: Player.cpp Player.h
$(OBJ_DIR)/GameConfig.o: GameConfig.cpp GameConfig.h
$(OBJ_DIR)/GameState.o: GameState.cpp GameState.h